### ISSUE TITLE
[Fix] 2.1.0 업데이트 설치 시 사용자 프로필에서 "실패"라고 생성되는 문제

### ISSUE THREAD

**Issue by jayn2u** [EAT-SSU/iOS#103]
# ⚠️ Bug Report

## 발견한 문제

> 정확한 문제와 상황을 적어주세요. 나중에 개발자가 다시 시연하기 편하게 상황까지 적어주시면 좋습니다.

- 업데이트 설치 시 사용자 프로필에서 "실패"라고 생성됩니다.
- 해당 문제는 로그아웃 후 재로그인하면 해결되는 부분인데, 개선해야 할 UX 입니다.

## 스크린샷

> 텍스트로 설명하기 어렵거나 편하게 이해하기 위해서는 발생한 문제의 스크린샷이나 동영상을 남겨주세요.

https://github.com/user-attachments/assets/661d565a-471d-480c-b9ef-bc047ea27101

## 플랫폼(iOS)

- 디바이스: iPhone X

## 기타 정보
> 앱 버전과 빌드번호는 `TestFlight`에서 확인하실 수 있습니다.

- 앱 버전: 2.1.0
- 빌드번호: 2.1.0.4

**Comment by CJiu01** [comment]
닉네임을 가져오는 로직이 바뀌면서 재로그인이 필수일 듯 하네요.

해당 문구를 `재로그인해주세요` 로 수정하는 건 어떤가요?

**Comment by HI-JIN2** [comment]
> 닉네임을 가져오는 로직이 바뀌면서 재로그인이 필수일 듯 하네요.
> 
> 해당 문구를 `재로그인해주세요` 로 수정하는 건 어떤가요?

최악인데요... 해당 기능 정상적으로 작동하게 수정 부탁드립니다! 🙏

**Comment by CJiu01** [comment]
이전 작업에서 해당 이슈 해결했습니다. 이슈 닫겠습니다.
