### ISSUE TITLE
[Feat] 앱 최소버전 확인 remote config 연동

### ISSUE THREAD

**Issue by CJiu01** [EAT-SSU/iOS#120]
# 📲 Feature Request

## 💡 세부업무

> 해야 할 업무에 대해서 설명해주세요!

- firebase remote config 를 통해 앱 동작에 필요한 최소 버전을 지정합니다.

## 📝 ETC

> 기타 설명이 필요하다면 작성해주세요!

**Comment by jayn2u** [comment]
해당 기능을 사용하면 앱스토어 심사가 거부되었습니다. `2.1.2` 버전이 반려되었습니다.
Apple에서 제공한 스크린샷을 확인해보니까, "인앱 업데이트" 화면에서 문제가 발생했다고 알려주었습니다.

**Comment by HI-JIN2** [comment]
> 해당 기능을 사용하면 앱스토어 심사가 거부되었습니다. `2.1.2` 버전이 반려되었습니다. Apple에서 제공한 스크린샷을 확인해보니까, "인앱 업데이트" 화면에서 문제가 발생했다고 알려주었습니다.

음 해당 기능을 써서는 아닐걸요..? 이전부터 리모트 컨피그로 업데이트 강제 걸어놨던걸로 알고 있어요..!

**Comment by jayn2u** [comment]
> > 해당 기능을 사용하면 앱스토어 심사가 거부되었습니다. `2.1.2` 버전이 반려되었습니다. Apple에서 제공한 스크린샷을 확인해보니까, "인앱 업데이트" 화면에서 문제가 발생했다고 알려주었습니다.
> 
> 음 해당 기능을 써서는 아닐걸요..? 이전부터 리모트 컨피그로 업데이트 강제 걸어놨던걸로 알고 있어요..!

흐음... 계속 연구를 해봐야 할 듯 합니다...

**Comment by CJiu01** [comment]
> > 해당 기능을 사용하면 앱스토어 심사가 거부되었습니다. `2.1.2` 버전이 반려되었습니다. Apple에서 제공한 스크린샷을 확인해보니까, "인앱 업데이트" 화면에서 문제가 발생했다고 알려주었습니다.
> 
> 음 해당 기능을 써서는 아닐걸요..? 이전부터 리모트 컨피그로 업데이트 강제 걸어놨던걸로 알고 있어요..!

아뇨! 이전까지 `인앱 업데이트`로 사용하고 있었습니다.
인앱 업데이트를 사용할 경우, 최소 버전 지정이 불가능하여 remote config 으로 개선하려 합니다.

**Comment by CJiu01** [comment]
이전에는 patch 또는 minor 버전이 업데이트될 경우, **강제 업데이트**로 설정해놓았습니다.
