### ISSUE TITLE
[Feat] 메인 화면 디자인 시스템 적용 및 카테고리 별 테이블 분리

### ISSUE THREAD

**Issue by CJiu01** [EAT-SSU/iOS#14]
# 🍎 iOS 이슈 발행

## 💡 세부업무

> 해야 할 업무에 대해서 설명해주세요!

- [ ] 메인 화면 디자인 시스템 적용
- [ ] 카테고리 별 테이블 분리

## 📝 ETC

> 기타 설명이 필요하다면 작성해주세요!

**Comment by HI-JIN2** [comment]
issue의 단위가 너무 큰 것 같아요. 한 번에 처리할 수 있을 만큼의 분량으로 나누어주세요!
