### ISSUE TITLE
[Refactor] MyPageViewController에서 비즈니스 로직 Model로 분리

### ISSUE THREAD

**Issue by jayn2u** [EAT-SSU/iOS#153]
# 🪄 Refactor request

## 설명

- 비대한 `Controller` 클래스에서 비즈니스 로직에 해당하는 부분들을 `Model`로 분리하겠습니다.

## 추가자료

- 추가자료를 첨부해주세요.

**Comment by CJiu01** [comment]
마이페이지 전체를 한 이슈에 잡기보다 단위를 작게 태스크를 세분화하는 건 어떤가요? (지난번 회의때도 이야기했지만 마이페이지에도 생각보다 태스크가 많더라구요!)

**Comment by jayn2u** [comment]
> 마이페이지 전체를 한 이슈에 잡기보다 단위를 작게 태스크를 세분화하는 건 어떤가요? (지난번 회의때도 이야기했지만 마이페이지에도 생각보다 태스크가 많더라구요!)

알겠습니당! 세분화해서 작업하는 건 좋은 것 같아요!
