### ISSUE TITLE
[Refactor] HomeVC Model 객체로 분리

### ISSUE THREAD

**Issue by CJiu01** [EAT-SSU/iOS#173]
# 🪄 Refactor request

## 설명

> HomeVC를 Model 객체로 분리합니다.

## 추가자료

> 추가자료를 첨부해주세요.

**Comment by jayn2u** [comment]
제가 슬랙에도 달아두었지만, 모델 객체로 분리하는 것이 아니라 레포지토리 계층과 같은 별개의 계층을 한 번 구상해서 작업해보았으면 좋겠습니다.
기대할게요!

**Comment by CJiu01** [comment]
안그래도 작업해주신 model 계층분리가 mvc 패턴일까에 대해 코드리뷰에서 한 번 이야기해보고 싶었는데, 거기까지가면 이번주 안에 못 끝낼 것 같아서 언급은 안했거든요.... 그럼 제가 따로 별개의 계층 구상해서 작업해봐도 될까요?

**Comment by CJiu01** [comment]
지금과 같은 방식의 작업은 단순히 코드 옮기기 작업...? 정도가 될 거 같아 큰 의미는 없을 것 같다고 생각을 합니다. 기간을 다음주까지로 해서 별개의 계층으로 구현해보는 것은 어떨까요?

**Comment by jayn2u** [comment]
좋습니다. 의아한 부분은 저에게도 많이 설명해주세요! 저도 많이 배우고 싶어서 잇슈팀에 온보딩 한거거든요.

**Comment by jayn2u** [comment]
이제 시간이 지난 경과로 리팩터링은 별개의 브랜치 말고 찬찬히 개별적으로 진행해주세요. 이슈는 닫겠습니다!
