### ISSUE TITLE
[Fix] 같은 이메일 사용자의 소셜 로그인 중복 문제 해결

### ISSUE THREAD

**Issue by jayn2u** [EAT-SSU/iOS#179]
# 🧰 Fix Request

## 📝 설명

> 할 일을 적어주세요.

- 예를 들어 카카오로 로그인 회원가입 했을 때, 애플로 로그인 시도시 아니라는 피드백을 주는 `UIAlertController` 설계

## 🗂️ 첨부자료

- 자료를 첨부해주세요.

**Comment by HI-JIN2** [comment]
#46 이미 등록되어 있는 이슈네요..

**Comment by jayn2u** [comment]
확인 굿 입니다!
