### ISSUE TITLE
[Refactor] MVC 적용을 위한 폴더 구조 수정

### ISSUE THREAD

**Issue by CJiu01** [EAT-SSU/iOS#180]
# 🪄 Refactor request

## 설명

> MVC 적용을 위해 폴더 구조를 수정합니다.

## 추가자료

> 추가자료를 첨부해주세요.

**Comment by jayn2u** [comment]
이제 시간이 지난 경과로 리팩터링은 별개의 브랜치 말고 찬찬히 개별적으로 진행해주세요. 이슈는 닫겠습니다!
