### ISSUE TITLE
[Refactor] UITableViewDataSource 객체 분리

### ISSUE THREAD

**Issue by CJiu01** [EAT-SSU/iOS#181]
# 🪄 Refactor request

## 설명

> UIViewController의 책임 분리를 위해 UITableViewDataSource 객체 분리합니다.

## 추가자료

> 추가자료를 첨부해주세요.

**Comment by CJiu01** [comment]
+ 다중 cell

**Comment by jayn2u** [comment]
이제 시간이 지난 경과로 리팩터링은 별개의 브랜치 말고 찬찬히 개별적으로 진행해주세요. 이슈는 닫겠습니다!
