### ISSUE TITLE
[Fix] 마이페이지 사용자 정보를 서버로부터 가져올 때 데이터가 로드되지 않는 UX 개선

### ISSUE THREAD

**Issue by jayn2u** [EAT-SSU/iOS#28]
# ⚠️ Bug Report

## 설명

- 사용자인터넷 환경에 기반해서 사용자 데이터를 가져오고 있는데, 화면이 로드되어야 데이터를 가져오는 로직이 실행되어서 해당 문제를 개선.
- 관심자 분리를 해서 네트워크 코드를 모델 객체로 분리해서 미리 데이터를 메모리에서 보관하고 있으면 UX를 개선할 수 있다고 생각함.
- 현재 첨부한 자료는 "다시 시도하세요" 문구가 없지만, 이런 경우가 종종 있기 때문에 개선할 수 있는 여지가 충분히 있다고 생각함.

## 첨부자료

https://github.com/user-attachments/assets/c9ec19d9-4f93-4528-b09c-36a6e17f616c

**Comment by HI-JIN2** [comment]
그외에도, 유저 닉네임 같은 경우에는 안드로이드의 sharedpreferences와 같은 가벼운 내장 디비(아마 자동로그인 로직하실때 사용하셨을 것 같습니다.)를 사용해서 저장하고 사용하면 해당 부분을 가볍게 처리할 수 있습니다~ 굳이 서버한테 받아야하는 값은 아니니까요. 

https://archijude.tistory.com/257
