### ISSUE TITLE
[Fix] 기존 디자인 플로우로 변경

### ISSUE THREAD

**Issue by binisnil** [EAT-SSU/iOS#31]
# 🍎 iOS 이슈 발행

## 💡 세부업무

> 해야 할 업무에 대해서 설명해주세요!

- [ ] 예시

## 📝 ETC

> 기타 설명이 필요하다면 작성해주세요!

**Comment by jayn2u** [comment]
조금 더 자세하게 적어주시면 감사하겠습니다!
