### ISSUE TITLE
[Fix] 일주일 중 토/일요일 푸드 코트 메뉴란의 height가 달라지는 문제

### ISSUE THREAD

**Issue by chaeyeon0130** [EAT-SSU/iOS#32]
# ⚠️ Bug Report

## 설명

> 설명을 적어주세요.
- 메뉴 페이지에서, 일주일 중 토/일요일만 푸드 코트 메뉴란의 height가 달라집니다.

## 첨부자료

> 자료를 첨부해주세요.

https://github.com/user-attachments/assets/c2ab7a69-ea01-4c39-aa12-dc6ca95cffbb

**Comment by jayn2u** [comment]
감사합니다!!!!
