### ISSUE TITLE
[Fix] 리뷰 신고 페이지 제목 오타

### ISSUE THREAD

**Issue by chaeyeon0130** [EAT-SSU/iOS#38]
# ⚠️ Bug Report

## 설명

> 설명을 적어주세요.
- 리뷰 신고 페이지에서 제목 문구가 완성되지 않았습니다.

## 첨부자료

> 자료를 첨부해주세요.

![image](https://github.com/user-attachments/assets/9b07ab31-fdf0-4001-b414-8d49df0433f9)

**Comment by HI-JIN2** [comment]
텍스트도 왼쪽 정렬인데, 피그마 디자인과 조금 다른 것 같아요~ 
<img width="261" alt="스크린샷 2024-09-14 오전 12 56 17" src="https://github.com/user-attachments/assets/f863382c-d0e1-4bf0-8a39-2f93f19d11b5">
