### ISSUE TITLE
[Fix] 리뷰 중복 작성됨

### ISSUE THREAD

**Issue by YUNSO99** [EAT-SSU/iOS#56]
# ⚠️ Bug Report

## 발견한 문제

두 개 이상의 메뉴를 선택하고 첫번째 메뉴 리뷰 입력 -> 두번째 메뉴 리뷰 입력 중 뒤로가기 -> 첫번째 메뉴 리뷰 화면 전환시
"다음 단계로" 버튼이 아닌 "리뷰 남기기" 버튼이 뜹니다.

## 스크린샷

https://github.com/user-attachments/assets/c26ec475-40c7-4bc4-8e95-efff6a4766ab

## 플랫폼(Android, iOS)

- 플랫폼: iOS
- 디바이스: 14 pro

## 기타 정보

- 앱 버전: 2.0.1.8

**Comment by HI-JIN2** [comment]
해당 이슈에 대한 부연 설명 덧붙입니다. 

1. A,B메뉴를 리뷰 달겠다고 체크함
2. A 리뷰 닮
3. B 리뷰 달다가 달기 싫어서 뒤로 감
4. A 리뷰 하단 버튼이 리뷰 남기기가 됨
5. 리뷰 남기기 를 눌렀더니, A 리뷰 정보(별점+텍스트)로 A랑 B 둘다 리뷰가 등록됨
