### ISSUE TITLE
[Feat] XCTest 프레임워크를 도입해서 모바일 앱 개발에서는 단위 테스트를 어떻게 가져가는지 조사

### ISSUE THREAD

**Issue by jayn2u** [EAT-SSU/iOS#59]
# 📲 Feature Request

## 💡 세부업무

> 해야 할 업무에 대해서 설명해주세요!

- 단위 테스트를 통해 CI 파이프라인에서 어떻게 활용할 수 있을지 리서치를 해봅니다.
- 해당 이슈는 PR과 연결해서 작업할 필요는 없다고 생각하고 있습니다.
- 단지 해야 할 일...

## 📝 ETC

> 기타 설명이 필요하다면 작성해주세요!

**Comment by CJiu01** [comment]
저도 관련해서 한 번 찾아볼께요👍
