### ISSUE TITLE
[Refactor] 폴더링 개편

### ISSUE THREAD

**Issue by jayn2u** [EAT-SSU/iOS#88]
# 🪄 Refactor request

## 설명

- Resources & Sources 예하 폴더들을 개편합니다.

## 추가자료

- 추가자료를 첨부해주세요.

**Comment by SAMBILI** [comment]
I think this will help you.
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
